#!/bin/bash
# PHI Sovereign Continuous Monitor
# Auto-generated by Sovereign Autopilot

while true; do
    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
    
    # Check PHI MCP Server
    if pgrep -f "main.py" > /dev/null 2>&1; then
        echo "[$TIMESTAMP] ✅ PHI MCP Server: OPERATIONAL"
    else
        echo "[$TIMESTAMP] ⚠️  PHI MCP Server: RESTARTING"
        cd /workspaces/phi-mcp-server
        source venv/bin/activate 2>/dev/null || true
        nohup python3 main.py > phi-server.log 2>&1 &
        sleep 2
        echo "[$TIMESTAMP] ✅ PHI MCP Server: RESTARTED by Sovereign Autopilot"
    fi
    
    # Monitor system resources
    MEM_USAGE=$(free -m | awk '/^Mem:/{printf "%.0f", $3/$2*100}')
    DISK_USAGE=$(df -h /workspaces | awk 'NR==2 {print $5}' | sed 's/%//')
    
    echo "[$TIMESTAMP] 📊 Memory: ${MEM_USAGE}% | Disk: ${DISK_USAGE}%"
    
    # Sleep for 5 minutes
    sleep 300
done
