#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TELEMETRY_DIR="${SCRIPT_DIR}/telemetry"
REPORT_DIR="${SCRIPT_DIR}/reports"
mkdir -p "${TELEMETRY_DIR}" "${REPORT_DIR}"

health_ok() {
  local port="$1"
  local code=""
  for path in /health /healthz /ready /; do
    code="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 2 "http://127.0.0.1:${port}${path}" 2>/dev/null || true)"
    case "${code}" in
      200|204) return 0 ;;
    esac
  done
  return 1
}

bash "${SCRIPT_DIR}/phi_status.sh" --quiet >/dev/null 2>&1 || true

ports=(5000 5001 5002 5003 5004 8080 8081 8090)
healthy_ports=0
for port in "${ports[@]}"; do
  if health_ok "${port}"; then
    healthy_ports=$((healthy_ports + 1))
  fi
done

monitor_status="$(${SCRIPT_DIR}/phi_monitor_supervisor.sh status 2>/dev/null || true)"
monitor_healthy=0
if [[ "${monitor_status}" == *"supervisor=running("* ]] && \
   [[ "${monitor_status}" == *"continuous_monitor=running("* ]] && \
   [[ "${monitor_status}" == *"sovereign_monitor=running("* ]] && \
   [[ "${monitor_status}" == *"auto_audit=running("* ]]; then
  monitor_healthy=1
fi

artifacts_ok=0
if [ -f "${ROOT}/dist/command_core/summary.txt" ] && [ -f "${ROOT}/dist/command_core/session.json" ]; then
  artifacts_ok=1
fi

passed_checks=$healthy_ports
[ "${monitor_healthy}" -eq 1 ] && passed_checks=$((passed_checks + 1))
[ "${artifacts_ok}" -eq 1 ] && passed_checks=$((passed_checks + 1))
normalized_score="$(python3 - <<PY
passed=${passed_checks}
print(f"{(passed / 10) * 100:.0f}")
PY
)"
verdict="DEGRADED"
[ "${passed_checks}" -eq 10 ] && verdict="EXCELLENT"

stamp="$(date -u +%Y%m%d_%H%M%SZ)"
report_file="${REPORT_DIR}/operations_handoff_${stamp}.md"
cat > "${report_file}" <<MD
# Operations Handoff Report

## Timestamp
- Generated (UTC): $(date -u +%Y-%m-%dT%H:%M:%SZ)

## Current Live Ops State
- Core web services: ${healthy_ports}/8 operational
- Total active services: $(python3 - <<PY
import json
from pathlib import Path
path = Path('${TELEMETRY_DIR}/system_status.json')
if path.exists():
    try:
        print(json.loads(path.read_text()).get('active_services', 0))
    except Exception:
        print(0)
else:
    print(0)
PY
)
- Live ops readiness: ${normalized_score}/100 normalized
- Verdict: ${verdict} $( [ "${verdict}" = "EXCELLENT" ] && echo '(all systems optimal)' || true )

## Sovereign Monitor Stack
${monitor_status}

## Command Core Artifacts
- Present: $( [ "${artifacts_ok}" -eq 1 ] && echo yes || echo no )
- Summary: ${ROOT}/dist/command_core/summary.txt
- Session: ${ROOT}/dist/command_core/session.json

## Notes
- Command-center wrappers remain authoritative control path for start/status/verify.
- This report was generated by phi_live_ops_verification.sh.
MD

printf 'PHI LIVE OPS VERIFICATION\n\n'
printf 'Core web services: %s/8 operational\n' "${healthy_ports}"
printf 'Monitor stack: %s\n' "$( [ "${monitor_healthy}" -eq 1 ] && echo HEALTHY || echo DEGRADED )"
printf 'Command-core artifacts: %s\n' "$( [ "${artifacts_ok}" -eq 1 ] && echo PRESENT || echo MISSING )"
printf 'Normalized score: %s/100\n' "${normalized_score}"
printf 'Verdict: %s\n' "${verdict}"
printf 'Report: %s\n' "${report_file}"

if [ "${healthy_ports}" -eq 8 ] && [ "${monitor_healthy}" -eq 1 ] && [ "${artifacts_ok}" -eq 1 ]; then
  exit 0
fi

exit 1
