#!/usr/bin/env bash
set -euo pipefail

# PHI Local Ops Autotuner
# Detects local hardware capabilities and emits stable high-performance defaults
# for local live operations, monitoring cadence, and intelligent sync behavior.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="${SCRIPT_DIR}/telemetry"
PROFILE_JSON="${LOG_DIR}/local_ops_profile.json"
PROFILE_ENV="${LOG_DIR}/local_ops_profile.env"
AUTOTUNE_LOG="${LOG_DIR}/local_ops_autotune.log"

mkdir -p "${LOG_DIR}"

log() {
  local message="$1"
  printf '[%s] %s\n' "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "$message" | tee -a "${AUTOTUNE_LOG}"
}

safe_int() {
  local raw="$1"
  if [[ "${raw}" =~ ^[0-9]+$ ]]; then
    printf '%s\n' "${raw}"
  else
    printf '%s\n' "0"
  fi
}

cpu_cores() {
  local detected
  detected="$(nproc 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)"
  safe_int "${detected}"
}

total_mem_gb() {
  local kb
  kb="$(awk '/MemTotal/ {print $2}' /proc/meminfo 2>/dev/null || echo 0)"
  if [[ "${kb}" =~ ^[0-9]+$ ]] && [ "${kb}" -gt 0 ]; then
    awk -v value="${kb}" 'BEGIN { printf "%d", (value/1024/1024)+0.5 }'
  else
    printf '0\n'
  fi
}

cpu_model() {
  local model
  model="$(lscpu 2>/dev/null | awk -F: '/Model name/ {gsub(/^[ \t]+/, "", $2); print $2; exit}' || true)"
  if [ -n "${model}" ]; then
    printf '%s\n' "${model}"
  else
    printf 'Unknown CPU\n'
  fi
}

gpu_model() {
  if command -v nvidia-smi >/dev/null 2>&1; then
    local model
    model="$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -n1 || true)"
    if [ -n "${model}" ]; then
      printf '%s\n' "${model}"
      return
    fi
  fi
  if command -v lspci >/dev/null 2>&1; then
    local pci_gpu
    pci_gpu="$(lspci | awk '/VGA|3D/ {print; exit}' || true)"
    if [ -n "${pci_gpu}" ]; then
      printf '%s\n' "${pci_gpu}"
      return
    fi
  fi
  printf 'none\n'
}

disk_free_gb() {
  local mount_point="${1:-/workspaces}"
  local value
  value="$(df -BG "${mount_point}" 2>/dev/null | awk 'NR==2 {gsub(/G/,"",$4); print $4}')"
  safe_int "${value:-0}"
}

io_profile() {
  local rot_file
  rot_file="/sys/block/$(df /workspaces 2>/dev/null | awk 'NR==2 {print $1}' | sed 's|/dev/||; s|p[0-9].*||')/queue/rotational"
  if [ -f "${rot_file}" ]; then
    if [ "$(cat "${rot_file}" 2>/dev/null || echo 1)" = "0" ]; then
      printf 'ssd\n'
      return
    fi
  fi
  printf 'unknown\n'
}

compute_profile() {
  local cores="$1"
  local mem_gb="$2"

  if [ "${cores}" -ge 24 ] && [ "${mem_gb}" -ge 64 ]; then
    printf 'ceiling\n'
  elif [ "${cores}" -ge 12 ] && [ "${mem_gb}" -ge 24 ]; then
    printf 'high\n'
  elif [ "${cores}" -ge 6 ] && [ "${mem_gb}" -ge 12 ]; then
    printf 'balanced\n'
  else
    printf 'safe\n'
  fi
}

derive_workers() {
  local cores="$1"
  local workers=$(( cores / 2 ))
  if [ "${workers}" -lt 2 ]; then
    workers=2
  fi
  if [ "${workers}" -gt 24 ]; then
    workers=24
  fi
  printf '%s\n' "${workers}"
}

derive_monitor_interval() {
  local profile="$1"
  case "${profile}" in
    ceiling) printf '20\n' ;;
    high) printf '30\n' ;;
    balanced) printf '45\n' ;;
    *) printf '60\n' ;;
  esac
}

derive_sync_interval() {
  local profile="$1"
  case "${profile}" in
    ceiling) printf '45\n' ;;
    high) printf '60\n' ;;
    balanced) printf '90\n' ;;
    *) printf '120\n' ;;
  esac
}

derive_parallel_jobs() {
  local cores="$1"
  local jobs=$(( cores - 1 ))
  if [ "${jobs}" -lt 2 ]; then
    jobs=2
  fi
  if [ "${jobs}" -gt 32 ]; then
    jobs=32
  fi
  printf '%s\n' "${jobs}"
}

write_profile() {
  local cores="$1"
  local mem_gb="$2"
  local cpu="$3"
  local gpu="$4"
  local free_gb="$5"
  local io="$6"
  local profile="$7"
  local workers="$8"
  local monitor_interval="$9"
  local sync_interval="${10}"
  local parallel_jobs="${11}"

  cat > "${PROFILE_JSON}" <<JSON
{
  "generated_at_utc": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')",
  "hardware": {
    "cpu_model": "${cpu}",
    "cpu_cores": ${cores},
    "memory_gb": ${mem_gb},
    "gpu": "${gpu}",
    "disk_free_gb_workspaces": ${free_gb},
    "io_profile": "${io}"
  },
  "runtime_profile": "${profile}",
  "autopilot": {
    "phi_max_sovereignty": true,
    "nhitl_mode": true,
    "worker_count": ${workers},
    "parallel_jobs": ${parallel_jobs}
  },
  "stability": {
    "monitor_interval_seconds": ${monitor_interval},
    "intelligent_sync_interval_seconds": ${sync_interval},
    "max_memory_percent": 88,
    "max_disk_percent": 90
  }
}
JSON

  cat > "${PROFILE_ENV}" <<ENV
# Generated by phi_local_ops_autotune.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')
export PHI_AUTOTUNE_PROFILE="${profile}"
export PHI_CPU_CORES="${cores}"
export PHI_MEMORY_GB="${mem_gb}"
export PHI_WORKER_COUNT="${workers}"
export PHI_PARALLEL_JOBS="${parallel_jobs}"
export PHI_MONITOR_INTERVAL="${monitor_interval}"
export PHI_INTELLIGENT_SYNC_INTERVAL="${sync_interval}"
export PHI_MAX_MEMORY_PERCENT="88"
export PHI_MAX_DISK_PERCENT="90"
ENV
}

main() {
  local cores mem_gb cpu gpu free_gb io profile workers monitor_interval sync_interval parallel_jobs

  cores="$(cpu_cores)"
  mem_gb="$(total_mem_gb)"
  cpu="$(cpu_model)"
  gpu="$(gpu_model)"
  free_gb="$(disk_free_gb /workspaces)"
  io="$(io_profile)"
  profile="$(compute_profile "${cores}" "${mem_gb}")"
  workers="$(derive_workers "${cores}")"
  monitor_interval="$(derive_monitor_interval "${profile}")"
  sync_interval="$(derive_sync_interval "${profile}")"
  parallel_jobs="$(derive_parallel_jobs "${cores}")"

  write_profile "${cores}" "${mem_gb}" "${cpu}" "${gpu}" "${free_gb}" "${io}" "${profile}" "${workers}" "${monitor_interval}" "${sync_interval}" "${parallel_jobs}"

  log "Autotune profile generated: ${profile}"
  log "Detected ${cores} cores, ${mem_gb}GB RAM, ${free_gb}GB free in /workspaces"
  log "Recommended workers=${workers}, monitor_interval=${monitor_interval}s, intelligent_sync_interval=${sync_interval}s"

  printf '%s\n' "${PROFILE_JSON}"
}

main "$@"
